### ISSUE TITLE
Is this in NPM?

### ISSUE THREAD

**Issue by DSchau** [honestica/angular-hot-reloader#6]
If it is, I cannot find it, and am being quite silly.

**Comment by FelixLC** [comment]
Hi @DSchau,
You're right, sorry, I just published it (and updated the readme): https://www.npmjs.com/package/angular-hot-reloader. It works well with our actual config but has not been tested outside. Please tell us if you have any issues with it

**Comment by DSchau** [comment]
Thanks, I'll be sure to give it a look and let you know if I run into any issues!
