### ISSUE TITLE
Does this support Typescript?

### ISSUE THREAD

**Issue by evanjmg** [honestica/angular-hot-reloader#7]
Would it support it if I used awesome-typescript-loader or webpack typescript loader for angular 1? I've been searching all over to implement Angular 1 Typescript hot reloading as Angular 2 gzipped is just too big for production ready mobile websites on 3G. I'll convert your example to typescript and see if it works :)

**Comment by FelixLC** [comment]
Hi ! Yes it supports typescript (we use typescript un pur current project). Please tell us if You have any issue implementing it,. I'll try to post an example with typescript if it helps.

**Comment by evanjmg** [comment]
Yes an example will help. I'm having a little trouble converting your example.

**Comment by jogjayr** [comment]
@evanjmg were you able to get it to work with TS?

**Comment by FelixLC** [comment]
Hello guys, sorry for the delay. The example now includes two components in typescript, (`counter.component` and `todo_item.component`). As an exercise you can swap the last lines of app.html with the counter component which is not used yet. I'll close the issue, but don't hesitate to comment here if you run through some issues.
